[project]
name = 'Tokenized-Digital-Identity-Sovereign-Control'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-sovereignty]
path = 'contracts/data-sovereignty.clar'
clarity_version = 2
epoch = 2.5

[contracts.portability]
path = 'contracts/portability.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
